# Site wide configuration
title: Data * Analysis + R
locale: en_US
description: "Blog of Chetan Prajapati"
favicon: favicon.ico
logo: null
search: true
url: "http://statistical-evidence.github.io"

# Jekyll configuration

permalink: /blog/:year/:title.html
paginate_path: /page:num/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

coderay:
  coderay_line_numbers: 
  coderay_line_numbers_start: 1
  coderay_tab_width: 4
  coderay_bold_every: 10
  coderay_css: class

mathjax: true
comments: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]

twittershare: http://twitter.com/share

# Site owner
owner:
  name: Chetan Prajapati
  avatar: chetan.jpg
  email: chetan.prajapati@live.com
  disqus-shortname: "chetan-prajapati"
  twitter: "chetan_oxforduk"
  facebook: "madhavmedstats"
  github: "statistical-evidence"
  stackexchange: "username"
  linkedin: "username"
  instagram: "username"
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #userid
  google:
    plus: #username
    analytics: UA-24186657-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
